USE [DB_130918_bitistry]
GO

/****** Object:  Table [dbo].[EQPets]    Script Date: 12/9/2022 7:47:48 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EQPets](
	[PetID] [int] IDENTITY(1,1) NOT NULL,
	[Owner] [varchar](15) NULL,
	[Pet] [varchar](15) NULL,
 CONSTRAINT [PK_EQPets] PRIMARY KEY CLUSTERED 
(
	[PetID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

