'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EQLogAnalyzer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Auspice, begins casting Auspice of the Hunter ,Raid,48
        '''CoP, begins casting Circle of Power ,Raid,120
        '''CoP, begin casting Circle of Power ,Raid,120
        '''GC, begins casting Guardian Circle ,Raid,120
        '''GC, begin casting Guardian Circle ,Raid,120
        '''Sham Epic, begins casting Prophet&apos;s Gift of the Ruchu.,Group,60
        '''Bard Epic, begins casting Spirit of Vesagran.,Group,60.
        '''</summary>
        Friend ReadOnly Property Buffs() As String
            Get
                Return ResourceManager.GetString("Buffs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CrPointer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CrPointer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property EQ_Log_Analyzer_FAQ() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("EQ_Log_Analyzer_FAQ", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LeftRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LeftRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to a babbling muck
        '''a baby oashim
        '''a backwards sphinx
        '''a bad actor
        '''a baelorat
        '''a baleful banshee
        '''a baleful blossom
        '''a baleful briar
        '''a baleful spirit
        '''a baleful stoneworker
        '''a ballista
        '''a ballroom dancer
        '''a bandit
        '''a bandit bear rider
        '''a bandit burrower
        '''a bandit foecrusher
        '''a bandit gutpiercer
        '''a bandit leader
        '''a bandit lookout
        '''a bandit pikeman
        '''a bandit tailor
        '''a bandit watcher
        '''a bane fragment
        '''a baneful shadow
        '''a baneful soul
        '''a banished efreeti
        '''a banished kerran
        '''a bank broker
        '''a bar patron
        '''a bar ser [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MobNames() As String
            Get
                Return ResourceManager.GetString("MobNames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gabab
        '''Gabanab
        '''Gabaner
        '''Gabann
        '''Gabantik
        '''Gabarab
        '''Gabarer
        '''Gabarn
        '''Gabartik
        '''Gabekab
        '''Gabeker
        '''Gabekn
        '''Gaber
        '''Gabn
        '''Gabobab
        '''Gabober
        '''Gabobn
        '''Gabobtik
        '''Gabtik
        '''Ganab
        '''Ganer
        '''Gann
        '''Gantik
        '''Garab
        '''Garanab
        '''Garaner
        '''Garann
        '''Garantik
        '''Gararab
        '''Gararer
        '''Gararn
        '''Garartik
        '''Garekab
        '''Gareker
        '''Garekn
        '''Garer
        '''Garn
        '''Garobab
        '''Garober
        '''Garobn
        '''Garobtik
        '''Gartik
        '''Gasab
        '''Gasanab
        '''Gasaner
        '''Gasann
        '''Gasantik
        '''Gasarab
        '''Gasarer
        '''Gasarn
        '''Gasartik
        '''Gasekab
        '''Gaseker
        '''Gasekn
        '''Gaser
        '''Gasn
        '''Gasobab
        '''Gasober
        '''Gasobn
        '''Gasobtik
        '''Gastik [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PetNames() As String
            Get
                Return ResourceManager.GetString("PetNames", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
